export var items = [
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. ",
    username: "User 1",
    distance: 1,
    rating: 4,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 2",
    distance: 2,
    rating: 2,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 3",
    distance: 1,
    rating: 2.5,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. ",
    username: "User 4",
    distance: 4,
    rating: 1.7,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 5",
    distance: 2,
    rating: 3.6,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 6",
    distance: 1,
    rating: 4.7,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. ",
    username: "User 7",
    distance: 3,
    rating: 5,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 8",
    distance: 2,
    rating: 2.3,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 9",
    distance: 4,
    rating: 3.5,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 10",
    distance: 4,
    rating: 4,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 11",
    distance: 4,
    rating: 2.9,
  },
  {
    profilePic: "https://images.ctfassets.net/usf1vwtuqyxm/6yl7KHNCnoctW5TGrOyNE1/d81e73479f15d2dfeb37dcf56c47b6b0/HP-F6-half-blood-prince-draco-malfoy-looking-concerned-web-landscape?fm=jpg&q=70&w=2560",
    bookTitle: "Harry Potter and the Prince of Slytherin by The Sinister Man",
    date: "December 1, 2019",
    bookCover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609896187i/31201472.jpg",
    bookDescription: "Harry Potter was Sorted into Slytherin after a crappy childhood. His brother Jim is believed to be the BWL. Think you know this story? Think again. Year Four starts on 9/1/20. NO romantic pairings prior to Fourth Year. Basically good Dumbledore and Weasleys. Limited bashing (mainly of James).",
    username: "User 12",
    distance: 4,
    rating: 0.5,
  }
]